name: train-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.2
  - pip:
    # Azure Machine Learning specific dependencies (do not change!)
    - azureml-defaults
    # Replace those with your own dependencies (either from your Conda env or requirements.txt)
    - pandas==0.25.3
